version: '3.3'

volumes:
  pg_data:
  static:
  media:
  static_frontend:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ../backend/foodgram/
    env_file: .env
    # Именнованные тома для статики и медиа в контейнера django.
    # Т.е. тут будет лежать статика и меди
    volumes:
      - static:/app/static_django/
      - media:/app/media/
    depends_on:
      - db 


  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      # Именнованый том. Место в контейнере
      # куда будет помещена собранная статика фронта.
      - static_frontend:/app/result_build/

  gateway:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      # Конфиг nginx, будет лежать в той же директории,
      # что и docker-compose.yaml чтобы мы сделали его доступным в контейнере.
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # Именнованные тома, которые будут доступны в backend
      # Директории в контейнере nginx, где будут лежать файлы backend.
      - static:/static_django/
      - media:/media/
      # Redoc. Файлы redoc помещаем в контейнер, по указанному пути.
      - ../docs/:/usr/share/nginx/html/api/docs/
      # Место в контейнере куда попадет статика фронта.
      - static_frontend:/static_frontend/
#      - ../frontend/build:/usr/share/nginx/html/

    depends_on:
      - backend